# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "3.7"

services:
  mariadb:
    image: mariadb:10.4
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_USER: bn_myapp
      MARIADB_DATABASE: bitnami_myapp
    networks:
      - app-network

  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - "8000:8000"
    entrypoint: ["./entrypoint.sh"]
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=qwerty
      - DB_DATABASE=bitnami_myapp
    networks:
      - app-network
    volumes:
      - "./todo-tasks:/app"
    depends_on:
      - mariadb

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data: